; =============================================================================
; Wizard of Wor Sound Browser - Injected Native Z80 Reference
; wow_sound_browser.lua v1.5.1-20260815-1140
;
; This listing represents the native Z80 browser loop and generated native
; WoW UI display list present in RAM in the supplied MAME capture.
;
; Verification:
;   $D400-$D414  21-byte foreground loop       byte-exact
;   $D420-$D525  262-byte generated UI code    byte-exact
;   $D600-$D7D3  468-byte initial UI strings   byte-exact
;
; $D418 is a runtime repaint flag.  Its captured idle value was $00.
; $DFE0 is the browser's private stack top; stack contents are runtime data
; and are not represented here.
;
; The gaps between the sections below are not browser code/data and are
; intentionally omitted.
;
; WoW native text encoding used in the captured strings:
;   @  blank glyph
;   _  dash glyph
;   a  selector/right-arrow glyph when a row is selected
;   ]  up-arrow glyph
;   ^  down-arrow glyph
; =============================================================================

WoW_Print_String_Color          EQU     $03B5
Sound_Request_Dispatch_Entry   EQU     $8003

UI_Draw_Pending                EQU     $D418
Browser_Stack_Top              EQU     $DFE0

XPAND_BLUE                     EQU     $04
XPAND_YELLOW                   EQU     $08
XPAND_RED                      EQU     $0C

; =============================================================================
; $D400-$D414 - Resident foreground loop
;
; Interrupts remain enabled.  Each interrupt advances WoW's normal periodic
; sound service.  After HALT returns, the loop calls WoW's native request
; dispatcher at $8003.  A pending UI repaint is serviced by the generated
; display list at $D420.
; =============================================================================

                                ORG     $D400

Browser_Foreground_Loop:
        EI                                      ; $D400
Browser_Halt:
        HALT                                    ; $D401
        CALL    Sound_Request_Dispatch_Entry    ; $D402

        LD      A,(UI_Draw_Pending)             ; $D405
        OR      A                               ; $D408
        JR      Z,Browser_Halt                  ; $D409

        XOR     A                               ; $D40B
        LD      (UI_Draw_Pending),A             ; $D40C
        CALL    Draw_Browser_UI                 ; $D40F
        JP      Browser_Halt                    ; $D412


; =============================================================================
; $D420-$D525 - Generated native UI display list
;
; Every display operation calls WoW's resident renderer at $03B5:
;   HL = native text
;   DE = native screen position
;   B  = character count
;   A  = expand color
;
; The instruction stream is generated by the Lua browser from a fixed layout.
; String contents at $D600+ are regenerated as selection and live sound state
; change, but the captured display-list structure is fixed.
; =============================================================================

                                ORG     $D420

Draw_Browser_UI:

; Row 0: column headings
        LD      HL,UI_Column_Header             ; $D420
        LD      DE,$0002
        LD      B,$18
        LD      A,XPAND_BLUE
        CALL    WoW_Print_String_Color

; Row 0: version, right aligned
        LD      HL,UI_Version                   ; $D42D
        LD      DE,$0048
        LD      B,$04
        LD      A,XPAND_BLUE
        CALL    WoW_Print_String_Color

; Catalog row 1
        LD      HL,UI_Catalog_Row_1             ; $D43A
        LD      DE,$0502
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_1            ; $D447
        LD      DE,$0500
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 2
        LD      HL,UI_Catalog_Row_2             ; $D454
        LD      DE,$0A02
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_2            ; $D461
        LD      DE,$0A00
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 3
        LD      HL,UI_Catalog_Row_3             ; $D46E
        LD      DE,$0F02
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_3            ; $D47B
        LD      DE,$0F00
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 4
        LD      HL,UI_Catalog_Row_4             ; $D488
        LD      DE,$1402
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_4            ; $D495
        LD      DE,$1400
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 5
        LD      HL,UI_Catalog_Row_5             ; $D4A2
        LD      DE,$1902
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_5            ; $D4AF
        LD      DE,$1900
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 6
        LD      HL,UI_Catalog_Row_6             ; $D4BC
        LD      DE,$1E02
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_6            ; $D4C9
        LD      DE,$1E00
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Catalog row 7
        LD      HL,UI_Catalog_Row_7             ; $D4D6
        LD      DE,$2302
        LD      B,$27
        LD      A,XPAND_RED
        CALL    WoW_Print_String_Color

        LD      HL,UI_Selector_Row_7            ; $D4E3
        LD      DE,$2300
        LD      B,$01
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

; Blank separator row
        LD      HL,UI_Blank_Row_8               ; $D4F0
        LD      DE,$2800
        LD      B,$28
        LD      A,XPAND_BLUE
        CALL    WoW_Print_String_Color

; Live primary/secondary engine state
        LD      HL,UI_Live_Status               ; $D4FD
        LD      DE,$2D00
        LD      B,$28
        LD      A,XPAND_BLUE
        CALL    WoW_Print_String_Color

; Blank separator row
        LD      HL,UI_Blank_Row_10              ; $D50A
        LD      DE,$3200
        LD      B,$28
        LD      A,XPAND_BLUE
        CALL    WoW_Print_String_Color

; One-line controls
        LD      HL,UI_Control_Line              ; $D517
        LD      DE,$3700
        LD      B,$28
        LD      A,XPAND_YELLOW
        CALL    WoW_Print_String_Color

        EI                                      ; $D524
        RET                                     ; $D525


; =============================================================================
; $D600-$D7D3 - Captured initial UI text
;
; This is the exact initial idle/unselected text image from the supplied RAM
; capture.  The Lua browser regenerates this data as the visible catalog,
; selection, live engine state, and control mode change.
; =============================================================================

                                ORG     $D600

UI_Column_Header:              DB      "REQ@@LVL@PRI@@SEC@@EVENT"           ; $D600, 24
UI_Version:                    DB      "V151"                               ; $D618, 4

UI_Catalog_Row_1:              DB      "R1B0@0@@@89BE@89E5@GLOBAL@EVENT@0@@@@@@" ; $D61C, 39
UI_Selector_Row_1:             DB      "@"                                  ; $D643, 1

UI_Catalog_Row_2:              DB      "R1B1@0@@@89A0@89AF@GLOBAL@EVENT@1@@@@@@" ; $D644, 39
UI_Selector_Row_2:             DB      "@"                                  ; $D66B, 1

UI_Catalog_Row_3:              DB      "R1B2@0@@@8741@8772@GLOBAL@EVENT@2@@@@@@" ; $D66C, 39
UI_Selector_Row_3:             DB      "@"                                  ; $D693, 1

UI_Catalog_Row_4:              DB      "R1B3@0@@@8981@____@GLOBAL@EVENT@3@@@@@@" ; $D694, 39
UI_Selector_Row_4:             DB      "@"                                  ; $D6BB, 1

UI_Catalog_Row_5:              DB      "R1B4@0@@@8A0C@8A27@GLOBAL@EVENT@4@@@@@@" ; $D6BC, 39
UI_Selector_Row_5:             DB      "@"                                  ; $D6E3, 1

UI_Catalog_Row_6:              DB      "R1B5@0@@@8971@____@COIN@UP@@@@@@@@@@@@@" ; $D6E4, 39
UI_Selector_Row_6:             DB      "@"                                  ; $D70B, 1

UI_Catalog_Row_7:              DB      "R2B0@1@@@____@8928@PLAYER@DEATH@@@@@@@@" ; $D70C, 39
UI_Selector_Row_7:             DB      "@"                                  ; $D733, 1

UI_Blank_Row_8:                DB      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" ; $D734, 40
UI_Live_Status:                DB      "LIVE@P@IDLE@@@____@@S@IDLE@@@____@@@@@@@" ; $D75C, 40
UI_Blank_Row_10:               DB      "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@" ; $D784, 40
UI_Control_Line:               DB      "]^@SELECT@FIRE@PLAY@1P@EXIT@2P@PLAY@ALL@" ; $D7AC, 40

; End of captured Lua-owned UI data: $D7D3.
