; wow_sound_browser.asm
; Wizard of Wor native injected sound browser
; Browser version 2.1.2-20260815-1342
;
; Native controller:       $D400-$D6F6
; Browser state/mailbox:   $D700-$D712
; Native UI program:       $D740-$D837
; Dynamic UI text/data:    $D900-$DADF
; Native request table:    $DB00-$DB2F
; Browser stack top:       $DFE0
;
; Lua validates the WoW ROM, installs the controller and request table, prepares
; the text display list, exposes console commands, and reports engine state.
; The injected Z80 controller polls WoW inputs and performs sound reset, request
; posting, dispatch, manual playback, and Play All through resident WoW code.
;
; $D400-$D6F6 corresponds to NATIVE_CODE in wow_sound_browser.lua.
; $D740-$D837 is the display program generated by write_native_draw_program().

; -----------------------------------------------------------------------------
; WoW sound RAM and resident entry points
; -----------------------------------------------------------------------------

Sound_Request_1                 EQU     $D240
Sound_Request_2                 EQU     $D241
Sound_Request_3                 EQU     $D242
Sound_Request_4                 EQU     $D243
Sound_Service_Enabled           EQU     $D244

Primary_Sound_Modulators        EQU     $D246
Primary_Sound_Engine_Record     EQU     $D270
Secondary_Sound_Modulators      EQU     $D282
Secondary_Sound_Engine_Record   EQU     $D2AC

Sound_Request_Dispatch          EQU     $8003
Init_All_Sound_Engines          EQU     $8006
Print_String_Color              EQU     $03B5

; -----------------------------------------------------------------------------
; Browser RAM
; -----------------------------------------------------------------------------

Browser_Draw_Code               EQU     $D740
Browser_Request_Table           EQU     $DB00
Browser_Stack_Top               EQU     $DFE0

Browser_Selection               EQU     $D700 ; 0-23
Browser_Active                  EQU     $D701 ; 0-23, $FF = none
Browser_Mode                    EQU     $D702 ; 0 = manual, 1 = Play All
Browser_Last_Controls           EQU     $D703
Browser_Last_Starts             EQU     $D704
Browser_Batch_Next              EQU     $D705
Browser_Batch_Completed         EQU     $D706
Browser_Sound_Timer             EQU     $D707
Browser_Gap_Timer               EQU     $D708
Browser_UI_Dirty                EQU     $D709
Browser_UI_Ready                EQU     $D70A
Browser_Exit_Request            EQU     $D70B
Browser_Mailbox_Command         EQU     $D70C
Browser_Mailbox_Argument        EQU     $D70D
Browser_Play_Sequence           EQU     $D70E
Browser_Stop_Sequence           EQU     $D70F
Browser_Stop_Reason             EQU     $D710 ; 1 idle, 2 fire, 3 replace, 4 limit, 5 Play All stop
Browser_Stop_Index              EQU     $D711
Browser_Batch_Result            EQU     $D712 ; 1 complete, 2 stopped

; Dynamic UI text addresses populated by Lua.
UI_Header                       EQU     $D900
UI_Row1_Text                    EQU     $D928
UI_Row1_Marker                  EQU     $D94F
UI_Row2_Text                    EQU     $D950
UI_Row2_Marker                  EQU     $D977
UI_Row3_Text                    EQU     $D978
UI_Row3_Marker                  EQU     $D99F
UI_Row4_Text                    EQU     $D9A0
UI_Row4_Marker                  EQU     $D9C7
UI_Row5_Text                    EQU     $D9C8
UI_Row5_Marker                  EQU     $D9EF
UI_Row6_Text                    EQU     $D9F0
UI_Row6_Marker                  EQU     $DA17
UI_Row7_Text                    EQU     $DA18
UI_Row7_Marker                  EQU     $DA3F
UI_Blank_Row8                   EQU     $DA40
UI_Status_Row9                  EQU     $DA68
UI_Blank_Row10                  EQU     $DA90
UI_Footer                       EQU     $DAB8

ORG     $D400
; -----------------------------------------------------------------------------
; Startup and foreground loop
; -----------------------------------------------------------------------------
Browser_Start:
    DI
    LD SP,Browser_Stack_Top
    CALL ClearRequests
    LD A,$01
    LD (Sound_Service_Enabled),A
    CALL Init_All_Sound_Engines
    XOR A
    LD (Browser_Selection),A
    LD (Browser_Mode),A
    LD (Browser_Last_Controls),A
    LD (Browser_Last_Starts),A
    LD (Browser_Batch_Next),A
    LD (Browser_Batch_Completed),A
    LD (Browser_Sound_Timer),A
    LD (Browser_Gap_Timer),A
    LD (Browser_UI_Ready),A
    LD (Browser_Exit_Request),A
    LD (Browser_Mailbox_Command),A
    LD (Browser_Mailbox_Argument),A
    LD (Browser_Play_Sequence),A
    LD (Browser_Stop_Sequence),A
    LD (Browser_Stop_Reason),A
    LD (Browser_Batch_Result),A
    LD A,$FF
    LD (Browser_Active),A
    ; Seed joystick/fire edge history before the first input poll.
    LD (Browser_Last_Controls),A
    LD A,$01
    LD (Browser_UI_Dirty),A
    JP Main_Loop

; Foreground service pass, synchronized to the WoW interrupt cadence.
Main_Loop:
    EI
    HALT
    DI
    CALL Sound_Request_Dispatch
    CALL ServiceMailbox
    CALL PollInputs
    CALL ServiceManual
    CALL ServicePlayAll
    LD A,(Browser_UI_Ready)
    OR A
    JR Z,Main_Loop
    XOR A
    LD (Browser_UI_Ready),A
    CALL Browser_Draw_Code
    JP Main_Loop

; Clear all four WoW sound-request bytes.
ClearRequests:
    XOR A
    LD (Sound_Request_1),A
    LD (Sound_Request_1+$01),A
    LD (Sound_Request_1+$02),A
    LD (Sound_Request_1+$03),A
    RET

; Reset request bytes and both resident WoW sound engines.
ResetAll:
    CALL ClearRequests
    CALL Init_All_Sound_Engines
    RET

; Mark the native menu for rebuild and redraw.
MarkDirty:
    LD A,$01
    LD (Browser_UI_Dirty),A
    RET

; Post the selected request through WoW RAM and dispatch it immediately.
; Request-table entry: byte 0 = bank offset from $D240, byte 1 = bit mask.
PlaySelected:
    CALL ResetAll
    LD A,(Browser_Selection)
    ADD A,A
    LD E,A
    LD D,$00
    LD HL,Browser_Request_Table
    ADD HL,DE
    LD C,(HL)
    INC HL
    LD B,(HL)
    LD HL,Sound_Request_1
    LD E,C
    LD D,$00
    ADD HL,DE
    LD (HL),B
    CALL Sound_Request_Dispatch
    LD A,(Browser_Selection)
    LD (Browser_Active),A
    XOR A
    LD (Browser_Sound_Timer),A
    LD A,(Browser_Play_Sequence)
    INC A
    LD (Browser_Play_Sequence),A
    CALL MarkDirty
    RET

; Publish the stop reason and advance the console trace sequence.
RecordStop:
    LD (Browser_Stop_Reason),A
    LD A,(Browser_Stop_Sequence)
    INC A
    LD (Browser_Stop_Sequence),A
    RET

; Stop the active manual sound.
StopCurrent:
    LD A,(Browser_Active)
    CP $FF
    RET Z
    LD (Browser_Stop_Index),A
    CALL ResetAll
    LD A,$02
    CALL RecordStop
    LD A,$FF
    LD (Browser_Active),A
    CALL MarkDirty
    RET

; FIRE toggles the selected sound or replaces the active sound.
ManualFire:
    LD A,(Browser_Mode)
    OR A
    JP NZ,BatchFire
    LD A,(Browser_Active)
    LD B,A
    LD A,(Browser_Selection)
    CP B
    JP Z,StopCurrent
    LD A,B
    CP $FF
    JR Z,ManualPlay
    LD (Browser_Stop_Index),A
    CALL ResetAll
    LD A,$03
    CALL RecordStop
ManualPlay:
    JP PlaySelected

; Catalog selection wraps across 24 entries.
MoveUp:
    LD A,(Browser_Selection)
    OR A
    JR Z,MoveUpWrap
    DEC A
    JR MoveStore
MoveUpWrap:
    LD A,$17
MoveStore:
    LD (Browser_Selection),A
    JP MarkDirty
MoveDown:
    LD A,(Browser_Selection)
    INC A
    CP 24
    JR C,MoveDownStore
    XOR A
MoveDownStore:
    LD (Browser_Selection),A
    JP MarkDirty

; Poll P1/P2 joystick/fire and 1P/2P Start using WoW input ports.
; Stored active-high input states provide press-edge detection.
PollInputs:
    IN A,($12)
    CPL
    AND $3F
    LD B,A
    IN A,($11)
    CPL
    AND $3F
    OR B
    LD C,A
    LD A,(Browser_Last_Controls)
    CPL
    AND C
    LD B,A
    LD A,C
    LD (Browser_Last_Controls),A
    LD A,(Browser_Mode)
    OR A
    JR NZ,PollBatchControls
    BIT 0,B
    CALL NZ,MoveUp
    BIT 1,B
    CALL NZ,MoveDown
    LD A,B
    AND $30
    CALL NZ,ManualFire
    JR PollStarts
PollBatchControls:
    LD A,B
    AND $30
    CALL NZ,BatchFire
PollStarts:
    IN A,($10)
    CPL
    AND $60
    LD C,A
    LD A,(Browser_Last_Starts)
    CPL
    AND C
    LD B,A
    LD A,C
    LD (Browser_Last_Starts),A
    BIT 5,B
    JR Z,NoExit
    LD A,$01
    LD (Browser_Exit_Request),A
NoExit:
    BIT 6,B
    CALL NZ,TogglePlayAll
    RET

; Console/admin mailbox commands:
;   1 = play Browser_Mailbox_Argument (0-23)
;   2 = stop
;   3 = toggle Play All
ServiceMailbox:
    LD A,(Browser_Mailbox_Command)
    OR A
    RET Z
    LD B,A
    XOR A
    LD (Browser_Mailbox_Command),A
    LD A,B
    CP 1
    JR NZ,MailStop
    LD A,(Browser_Mailbox_Argument)
    CP 24
    RET NC
    LD (Browser_Selection),A
    CALL MarkDirty
    JP ManualFire
MailStop:
    CP 2
    JR NZ,MailToggle
    LD A,(Browser_Mode)
    OR A
    JP NZ,StopPlayAll
    JP StopCurrent
MailToggle:
    CP 3
    RET NZ
    JP TogglePlayAll

; Detect natural completion of a manually played sound.
ServiceManual:
    LD A,(Browser_Mode)
    OR A
    RET NZ
    LD A,(Browser_Active)
    CP $FF
    RET Z
    LD (Browser_Stop_Index),A
    CALL EnginesIdle
    OR A
    RET Z
    LD A,$01
    CALL RecordStop
    LD A,$FF
    LD (Browser_Active),A
    JP MarkDirty

; 2P toggles native Play All.
TogglePlayAll:
    LD A,(Browser_Mode)
    OR A
    JP NZ,StopPlayAll
    CALL ResetAll
    LD A,$01
    LD (Browser_Mode),A
    XOR A
    LD (Browser_Selection),A
    LD (Browser_Batch_Next),A
    LD (Browser_Batch_Completed),A
    LD (Browser_Sound_Timer),A
    LD (Browser_Batch_Result),A
    LD A,$01
    LD (Browser_Gap_Timer),A
    LD A,$FF
    LD (Browser_Active),A
    JP MarkDirty

; Stop the current sound and end Play All.
StopPlayAll:
    LD A,(Browser_Active)
    CP $FF
    JR Z,StopAllNoRecordReset
    LD (Browser_Stop_Index),A
    CALL ResetAll
    LD A,$05
    CALL RecordStop
    JR StopAllNoRecord
StopAllNoRecordReset:
    CALL ResetAll
StopAllNoRecord:
    XOR A
    LD (Browser_Mode),A
    LD (Browser_Gap_Timer),A
    LD A,$02
    LD (Browser_Batch_Result),A
    LD A,$FF
    LD (Browser_Active),A
    JP MarkDirty

; FIRE during Play All stops the current sound and advances after the gap.
BatchFire:
    LD A,(Browser_Active)
    CP $FF
    RET Z
    LD (Browser_Stop_Index),A
    CALL ResetAll
    LD A,$02
    CALL RecordStop
    LD A,$02
    JP FinishBatch

; Complete one Play All item and arm the 45-tick inter-sound gap.
FinishBatch:
    LD A,$FF
    LD (Browser_Active),A
    LD A,(Browser_Batch_Completed)
    INC A
    LD (Browser_Batch_Completed),A
    LD A,$2D
    LD (Browser_Gap_Timer),A
    JP MarkDirty

; Advance Play All. Active sounds are limited to 240 foreground ticks.
ServicePlayAll:
    LD A,(Browser_Mode)
    OR A
    RET Z
    LD A,(Browser_Active)
    CP $FF
    JR Z,BatchNoActive
    LD (Browser_Stop_Index),A
    LD A,(Browser_Sound_Timer)
    INC A
    LD (Browser_Sound_Timer),A
    CP 240
    JR NC,BatchLimit
    CALL EnginesIdle
    OR A
    RET Z
    LD A,$01
    CALL RecordStop
    JP FinishBatch
BatchLimit:
    CALL ResetAll
    LD A,$04
    CALL RecordStop
    JP FinishBatch
BatchNoActive:
    LD A,(Browser_Gap_Timer)
    OR A
    JR Z,BatchStartNext
    DEC A
    LD (Browser_Gap_Timer),A
    RET
BatchStartNext:
    LD A,(Browser_Batch_Next)
    CP 24
    JR NC,BatchComplete
    LD (Browser_Selection),A
    INC A
    LD (Browser_Batch_Next),A
    JP PlaySelected
BatchComplete:
    XOR A
    LD (Browser_Mode),A
    LD A,$01
    LD (Browser_Batch_Result),A
    JP MarkDirty

; Return A=1 when both WoW software sound engines are idle.
EnginesIdle:
    LD IX,Primary_Sound_Engine_Record
    LD HL,Primary_Sound_Modulators
    CALL EngineIdle
    OR A
    RET Z
    LD IX,Secondary_Sound_Engine_Record
    LD HL,Secondary_Sound_Modulators
    JP EngineIdle

; IX = engine record, HL = first of six 7-byte modulator slots.
; Idle requires ready=0, wait=0, all modulators clear, and silent volume state.
EngineIdle:
    LD A,(IX+$11)
    OR A
    JR NZ,EngineNotIdle
    LD A,(IX+$0D)
    OR A
    JR NZ,EngineNotIdle
    LD B,6
EngineModLoop:
    LD A,(HL)
    OR A
    JR NZ,EngineNotIdle
    LD DE,$0007
    ADD HL,DE
    DJNZ EngineModLoop
    LD A,(IX+$05)
    OR A
    JR NZ,EngineNotIdle
    LD A,(IX+$06)
    AND $0F
    JR NZ,EngineNotIdle
    LD A,(IX+$06)
    AND $20
    JR Z,EngineIdleYes
    LD A,(IX+$04)
    AND $F0
    JR NZ,EngineNotIdle
EngineIdleYes:
    LD A,$01
    RET
EngineNotIdle:
    XOR A
    RET

; -----------------------------------------------------------------------------
; Generated native UI display program
;
; Lua populates the text/marker bytes at $D900-$DADF and generates this
; display-list structure at $D740-$D837. Row 9 contains engine status.
; Each entry calls WoW's $03B5 print routine. Browser_UI_Ready gates execution.
; -----------------------------------------------------------------------------

            ORG     $D740
Browser_Draw_Program:
    LD HL,UI_Header
    LD DE,$0000
    LD B,$28
    LD A,$04
    CALL Print_String_Color
    LD HL,UI_Row1_Text
    LD DE,$0502
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row1_Marker
    LD DE,$0500
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row2_Text
    LD DE,$0A02
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row2_Marker
    LD DE,$0A00
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row3_Text
    LD DE,$0F02
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row3_Marker
    LD DE,$0F00
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row4_Text
    LD DE,$1402
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row4_Marker
    LD DE,$1400
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row5_Text
    LD DE,$1902
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row5_Marker
    LD DE,$1900
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row6_Text
    LD DE,$1E02
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row6_Marker
    LD DE,$1E00
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Row7_Text
    LD DE,$2302
    LD B,$27
    LD A,$0C
    CALL Print_String_Color
    LD HL,UI_Row7_Marker
    LD DE,$2300
    LD B,$01
    LD A,$08
    CALL Print_String_Color
    LD HL,UI_Blank_Row8
    LD DE,$2800
    LD B,$28
    LD A,$04
    CALL Print_String_Color
    LD HL,UI_Status_Row9
    LD DE,$2D00
    LD B,$28
    LD A,$04
    CALL Print_String_Color
    LD HL,UI_Blank_Row10
    LD DE,$3200
    LD B,$28
    LD A,$04
    CALL Print_String_Color
    LD HL,UI_Footer
    LD DE,$3700
    LD B,$28
    LD A,$08
    CALL Print_String_Color
    RET

; -----------------------------------------------------------------------------
; Native request table
;
; Two bytes per catalog entry:
;   byte 0 = request-bank offset from $D240
;   byte 1 = request bit mask
; -----------------------------------------------------------------------------

            ORG     Browser_Request_Table
Browser_Request_Table_Data:
            DB      $00,$01        ; R1B0
            DB      $00,$02        ; R1B1
            DB      $00,$04        ; R1B2
            DB      $00,$08        ; R1B3
            DB      $00,$10        ; R1B4
            DB      $00,$20        ; R1B5
            DB      $01,$01        ; R2B0
            DB      $01,$02        ; R2B1
            DB      $01,$04        ; R2B2
            DB      $01,$08        ; R2B3
            DB      $01,$10        ; R2B4
            DB      $01,$40        ; R2B6
            DB      $01,$80        ; R2B7
            DB      $02,$01        ; R3B0
            DB      $02,$02        ; R3B1
            DB      $02,$04        ; R3B2
            DB      $02,$08        ; R3B3
            DB      $02,$10        ; R3B4
            DB      $02,$20        ; R3B5
            DB      $02,$80        ; R3B7
            DB      $03,$01        ; R4B0
            DB      $03,$02        ; R4B1
            DB      $03,$04        ; R4B2
            DB      $03,$08        ; R4B3
